#!/usr/bin/env ruby
Dir['./*.rb'].each { |file| require file }

class Gemfiler
  attr :gem_name, :option1, :option2

  def initialize(gem_name, option1, option2 = nil)
    @gem_name = gem_name
    @option1 = option1
    @option2 = option2
  end
end

case ARGV.length
when 3
  gemfiler = Gemfiler.new(ARGV[0], ARGV[1], ARGV[2])
when 2
  gemfiler = Gemfiler.new(ARGV[0], ARGV[1])
else raise ArgumentError, "Check your parameters !"
end

reciever = Reciever.new
unless ARGV[2]
  reciever.recieve(gemfiler.gem_name, gemfiler.option1)
else
  reciever.recieve(gemfiler.gem_name, gemfiler.option1, gemfiler.option2)
end
lookuper = LookUper.new(reciever.gem_name, reciever.option1, reciever.option2)
lookuper.lookup
printer = Printer.new(lookuper.cache_array, lookuper.gem_name, lookuper.option1, lookuper.option2)
printer.print_result
