# frozen_string_literal: true
source 'https://rubygems.org'
ruby '2.1.3'

gem 'multi_json',         '1.12.1'
gem 'i18n',               '0.7.0'
gem 'rack',               '1.6.4'
gem 'thin',               '1.7.0'
gem 'ohm',                '3.0.3'
gem 'ohm-contrib',        '3.0.0'
gem 'telegram-bot-ruby',  '0.6.0.2'
