#!/usr/bin/env ruby
Dir['./*.rb'].each { |f| require(f) }
require 'optparse'
parser = OptionParser.new do|opts|
  opts.banner = "Usage: ./gemfiler [gem_name] [gem_versions]
  Examples: ./gemfiler devise '~> 2.1.3'
            ./gemfiler rails '>= 3.1' '< 4.0'"
end

parser.parse!

gem_name, gem_version1, gem_version2 = ARGV

begin
  versions = VersionParser.new(gem_name).parse
  filtred_versions = VersionFilter.new(versions).filter(gem_version1, gem_version2)
  Outprinter.new(versions, filtred_versions).print
rescue ArgumentError
  puts "Error. Write gem's name first, than his version. Type './gemfiler -h' for help"
end
