class Animation
	def anim_arr=(arr)
    @anim_arr = arr
  end

  def anim_arr
    @anim_arr
  end

	def show_anim
		5.downto(1) do
			anim_arr.each do |x|
				puts x
				sleep(0.15)
				system("clear")
			end
		end
	end
end


keyboard_smash = ["MMMMMM_______________________________________________________________________________________MMMMMMM
MMMMM_____________________________MMMMMMM______________________________________________________MMMMM
MMMM____________________________MMMMMMMMMMMM____________________________________________________MMMM
MMMM__________________________MMMMMMMMMMMMMMM___________________________________________________MMMM
MMMM_________________________MMMMMMMMMMMMMMMMM__________________________________________________MMMM
MMMM_________________________MMMMMMMMMMMMMMMMM__________________________________________________MMMM
MM___________________________MMMMMMMMMMMMMMMMM____________________MMMMMMMM_______________________MMM
MM____________________________MMMMMMMMMMMMMMM_____________________MMMMMMMMMMMMMMMMMM_____________MMM
MM_____________________________MMMMMMMMMMMMMM_____________________MMMMMMMMMMMMMMMMMM_____________MMM
MM________________________MMMM__MMMMMMMMMMM_______________________MMMMMMMMMMMMMMMMMM_____________MMM
MM______________________MMMMMMMM___MMMMM__________________________MMMMMMMMMMMMMMMMMMM____________MMM
MM_____________________MMMMMMMMMMM________________________________MMMMMMMMMMMMMMMMMMMMM__________MMM
MM____________________MMMMMMMMMMMM________________________________MMMMMMMMMMMMMMMMM__MM__________MMM
MM___________________MMMMMMMMMMMMMM_______________________________________MMMMMM_____MMM_________MMM
MM_______MM_________MMMMMMMMMMMMMMM_______________________________________MMMMMM_____MMM_________MMM
MM_______MMM_______MMMMMMMMMMMMMMMM______________________________MMMMMMMMMMMMMMMMMMM__MMM________MMM
MM_______MMMM_____MMMMMMMMMMMMMMMMMM_____________________________MMMMMMMMMMMMMMMMMMM__MMM________MMM
MM_______MMMM_____MMMMMMMMMMMMMMMMMMM_____________MMMMMMMMMMM___MMMMMMMMMMMMMMMMMMMMM_MMM________MMM
MM_______MMMMM___MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM________MMM
MM_______MMMMM__MMMMMMMMMMMMMMMMMM___MMMMMMMMMMMMMMMMMMMMMMMMM__MMMMMMMMMMMMMMMMMMM__MMMM________MMM
MM_______MMMMM__MMMMMMMMMMMMMMMMMM___MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MM________MMM
MM_______MMMMM__MMMMMMMMMMMMMMMMMM__MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MM________MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMM___________MMMMM_________________________MMMM________MMM_______MMM
MM______MMMMM__MMMMMMMMMMMMMMMMMMM____________MMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMM___________MMMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMM___________MMMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MMMM__________________________MMMM________MMM_______MMM
MM______MMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM______MMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM___MMMMMMMMMMMMMMMMMMMMM____MMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMMMMMMMMMMMMMMMMMMMMMMMMMM____MMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMMMMMM_________MM_____________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM____________________MMMMM____________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM________________MMMM_MMMM____________MMMMM_MMMM__________________________MMMM________MMM_______MMM
MM_____________MMMM____MMMMM___________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM_____________________MMMMM___________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM_____________MMMMMMMMMMMMMMMMMMM_____MMMMM_MMMM__________________________MMMM________MMM_______MMM
MM_____________MMMMMMMMM__MMMMMMMMM____MMMMM_MMMMM_________________________MMMM________MMM_______MMM
MMMM____________MM______MM_____MMM_____MMMMM__MMM__________________________MMMM________MMM______MMMM
MMMM____________MMM____MMMM____MMM______________________________________________________________MMMM",
"MMMMMM_______________________M_______________________________________________________________MMMMMMM
MMMMM_____________________MMMMMM_______________________________________________________________MMMMM
MMMM______________________MMMMMM_________________________MM_____________________________________MMMM
MMMM________________________MM_________________________MMMMMM___________________________________MMMM
MMMM___________________________________MMMMMMM_________MMMMMM___________________________________MMMM
MMMM________________________________MMMMMMMMMMMMM________MM_____________________________________MMMM
MM_________________________________MMMMMMMMMMMMMMM________________MMMMMMMM_______________________MMM
MM________________________________MMMMMMMMMMMMMMMMM_______________MMMMMMMMMMMMMMMMMM_____________MMM
MM________________________________MMMMMMMMMMMMMMMMM_______________MMMMMMMMMMMMMMMMMM_____________MMM
MM________________________________MMMMMMMMMMMMMMMMM_______________MMMMMMMMMMMMMMMMMM_____________MMM
MM_________________________________MMMMMMMMMMMMMMM________________MMMMMMMMMMMMMMMMMMM____________MMM
MM___________________________MMMMMMMMMMMMMMMMMMMMM________________MMMMMMMMMMMMMMMMMMMMM__________MMM
MM________________________MMMMMMMMMMMMMMMMMMMMMM__________________MMMMMMMMMMMMMMMMM_MMM__________MMM
MM______________________MMMMMMMMMMMMMM__MMMMM_____________________________MMMMMM_____MMM_________MMM
MM_______MM___________MMMMMMMMMMMMMMMM____________________________________MMMMMM_____MMM_________MMM
MM_______MMM_________MMMMMMMMMMMMMMMMM___________________________MMMMMMMMMMMMMMMMMMM__MMM________MMM
MM_______MMMM______MMMMMMMMMMMMMMMMMM____________________________MMMMMMMMMMMMMMMMMMM__MMM________MMM
MM_______MMMM______MMMMMMMMMMMMMMMMMMM____________MMMMMMMMMMM____MMMMMMMMMMMMMMMMMMMM_MMM________MMM
MM_______MMMM_____MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM________MMM
MM_______MMMMM___MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MMMMMMMMMMMMMMMMMMM__MMMM________MMM
MM_______MMMMM__MMMMMMMMMMMMMMMMMMMM_MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MM________MMM
MM_______MMMMM__MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MMM_______MMM
MM______MMMMMM__MMMMMMMMMMMMMMMMMMMM_________MMMMM_________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMMM__________MMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMM__________MMMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMM__________MMMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MMMM__________________________MMMM________MMM_______MMM
MM______MMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM______MMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM___MMMMMMMMMMMMMMMMMMMMM____MMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMMMMMMMMMMMMMMMMMMMMMMMMMM____MMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMMMMMM_________MM_____________MMMMM_MMMM__________________________MMMM________MMM_______MMM
MMM___________________MMMMM____________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM________________MMMM_MMMM____________MMMMM_MMMM__________________________MMMM________MMM_______MMM
MM_____________MMMMM___MMMMM___________MMMMM__MMM__________________________MMMM________MMM_______MMM
MMM____________________MMMMM___________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM_____________MMMMMMMMMMMMMMMMMMM_____MMMMM_MMMMM_________________________MMMM________MMM_______MMM
MM_____________MMMMMMMMM__MMMMMMMMM____MMMMM_MMMMM_________________________MMMM________MMM_______MMM
MMMM____________MMM_____MM_____MMM_____MMMMM__MMM__________________________MMMM________MMM______MMMM
MMMM____________MMM____MMMM____MMM______________________________________________________________MMMM",
"MMMMMM________________________MM_____________________________________________________________MMMMMMM
MMMMM_____________________MM_MMMM_MM___________________________________________________________MMMMM
MMMM_______________________MMMMMMMM______________________M______________________________________MMMM
MMMM_______________________MMMMMMMM_____________________MMM_____________________________________MMMM
MMMM______________________MMMMMMMMMM_________________MMMMMMMMM__________________________________MMMM
MMMM__________________________MM_____________________MMMMMMMM___________________________________MMMM
MM__________________________________________________MMMMMMMMMM____MMMMMMMM_______________________MMM
MM______________________________________________________MMM_______MMMMMMMMMMMMMMMMMM_____________MMM
MM__________________________________________MMMMM_________________MMMMMMMMMMMMMMMMMM_____________MMM
MM_______________________________________MMMMMMMMMMM______________MMMMMMMMMMMMMMMMMM_____________MMM
MM_____________________________________MMMMMMMMMMMMMM_____________MMMMMMMMMMMMMMMMMMM____________MMM
MM____________________________________MMMMMMMMMMMMMMMM____________MMMMMMMMMMMMMMMMMMMM___________MMM
MM__________________________MMMMMMMMMMMMMMMMMMMMMMMMMMM___________MMMMMMMMMMMMMMMMM__MM__________MMM
MM_______________________MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM___________________MMMMMM_____MMM_________MMM
MM_______MMM___________MMMMMMMMMMMMMM_MMMMMMMMMMMMMMMM____________________MMMMMM_____MMM_________MMM
MM_______MMM_________MMMMMMMMMMMMMMMM__MMMMMMMMMMMMMMM___________MMMMMMMMMMMMMMMMMMM__MMM________MMM
MM_______MMMM_______MMMMMMMMMMMMMMMMM___MMMMMMMMMMMM_____________MMMMMMMMMMMMMMMMMMM__MMM________MMM
MM_______MMMM______MMMMMMMMMMMMMMMMMMM____MMMMMMMMM__MMMMMMMM____MMMMMMMMMMMMMMMMMMMM_MMM________MMM
MM_______MMMMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM________MMM
MM_______MMMMM___MMMMMMMMMMMMMMMMMMMM_MMMMMMMMMMMMMMMMMMMMMMMM__MMMMMMMMMMMMMMMMMMM__MMMM________MMM
MM_______MMMMM___MMMMMMMMMMMMMMMMMMM_MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MM________MMM
MM_______MMMMM__MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MM________MMM
MM______MMMMMM__MMMMMMMMMMMMMMMMMMMM_________MMMMM_________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMM___________MMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMM__________MMMM__________________________MMMM________MMM_______MMM
MM______MMMMMM_MMMMMMMMMMMMMMMMMMMM__________MMMM__________________________MMMM________MMM_______MMM
MM______MMMMM__MMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MMMM__________________________MMMM________MMM_______MMM
MM______MMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM____MMMMMMMMMMMMMMMMMMMMMMMMMMMMM_MMMM__________________________MMMM________MMM_______MMM
MM______MMM______MMMMMMMMMMMMMMMMMMMMMMMMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMM___MMMMMMMMMMMMMMMMMMMMM____MMMMM_MMMM__________________________MMMM________MMM_______MMM
MM______MMMMMMMMMMMMMMMMMMMMMMMMMMM____MMMMM__MMM__________________________MMMM________MMM_______MMM
MM______MMMMMMM_________MM_____________MMMMM__MMM__________________________MMMM________MMM_______MMM
MMM___________________MMMMM____________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM________________MMMM_MMMM____________MMMMM_MMMM__________________________MMMM________MMM_______MMM
MM_____________MMMMM___MMMMM___________MMMMM__MMM__________________________MMMM________MMM_______MMM
MMM____________________MMMMM___________MMMMM__MMM__________________________MMMM________MMM_______MMM
MM_____________MMMMMMMMMMMMMMMMMMM_____MMMMM_MMMMM_________________________MMMM________MMM_______MMM
MM_____________MMMMMMMMM__MMMMMMMM_____MMMMM_MMMMM_________________________MMMM________MMM_______MMM
MMMM____________MM______MM_____MMM_____MMMMM__MMM__________________________MMMM________MMM______MMMM
MMMM____________MMM____MMMM____MMM______________________________________________________________MMMM"]

a = Animation.new
a.anim_arr=(keyboard_smash)
a.show_anim