#!/usr/bin/env ruby
require_relative 'chooser.rb'
require_relative 'parser.rb'
require_relative 'colorizer.rb'

if ARGV.size < 2
  puts 'Incorrect number of arguments'
else
  versions = Parser.parse_str(ARGV[0]) #Exception not null
  versions_matched = Chooser.match_versions(versions, ARGV.slice(1, ARGV.size - 1).to_a)
  Colorizer.colorize_matched(versions_matched)
end