source 'https://rubygems.org'
ruby "2.3.0"

gem  "sinatra"
gem  "activerecord"
gem  "sinatra-activerecord"
gem  "rake"


group :development do
 gem 'sqlite3'
end

group :production do
  gem 'sqlite3'
end
