# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'telegram-bot-ruby'
gem 'pry'
gem 'mechanize'
gem 'json'
gem 'translit'
gem 'fuzzy_match'
gem 'rubocop'
