#!/usr/bin/env ruby
#require 'pry'
Dir['../lib/*.rb'].each { |f| require_relative(f) }

if ARGV.size <2
	raise ArgumentError
end

name , condition=ARGV

#if name.match("([0-9a-zA-Z_])*").to_s != name
 # raise ArgumentError
#end

#if condition.match("[!=><~]{1,2}(([0-9])*[.])*([0-9a-zA-z])*").to_s != condition
 # raise ArgumentError
#end
unless (name =~ /\w+/) && (specifier =~ /[~><][=>]\s*(\d+\.)*\d+/)
  raise ArgumentError
end

versions  = VersionFetcher.new(name).fetch

filtered_versions  = VersionFilter.new(versions).filter(specifier)
Visualizer.new(versions,filtered_versions).visualize

