#!/usr/bin/env ruby

Dir['../lib/*.rb'].each { |f| require_relative(f) }

if ARGV.size < 2
  raise ArgumentError
end

name, condition = ARGV

unless (name =~ /\w+/) && (specifier =~ /[~><][=>]\s*(\d+\.)*\d+/)
  raise ArgumentError
end

versions = VersionFetcher.new(name).fetch

filtered_versions = VersionFilter.new(versions).filter(specifier)

Visualizer.new(versions,filtered_versions).visualize

