#!/usr/bin/env ruby

def binary(n, bin)
  bin.to_i.to_s(2).reverse.chars.map do |b|
    if n > 0
      n -= 1 if b == '1'
      '0'
    else
      b
    end
  end.join.reverse.to_i(2)
end

stck = []

loop do
  tmp = gets
  tmp.chomp!
  if tmp =~ /\A\d+\z/
    stck.push(tmp.to_i)
  elsif ['+', '-', '*', '/', '!'].include? tmp
    case tmp
    when '!' then stck.push(binary(stck.pop, stck.pop))
    else stck.push(stck.pop(2).inject(tmp.to_sym))
    end
    break if stck.count == 1
  end
end

puts '#=> ' + stck.pop.to_s
