# frozen_string_literal: true
source 'https://rubygems.org'
#source 'http://gemcutter.org'
#source 'http://gems.github.com'
#source 'http://gems.rubyforge.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'mechanize'
gem 'telegram-bot-ruby'
gem 'translit'
gem 'gingerice'