source 'https://rubygems.org'

gem 'OptionParser', '~> 0.5.1'
gem 'mechanize', '~> 2.7', '>= 2.7.3'
gem 'colorize', '~> 0.7.7'
gem 'unicode', '~> 0.4.4.2'
gem 'colored', '~> 1.2'
#gem 'nokogiri', '~> 1.6', '>= 1.6.6.2'
