#!usr/bin/env ruby

skeleton = []
skeleton[0] = '
`````````````````XYiTTTTIXB```````````````````````````````
`````````````B_``````````_iiiTB```````````````````````````
```````````B``````````i__iTYTYIYIX````````````````````````
``````````Y``````````iiTiTTTTYYIIYIB``````````````````````
`````````Y`````````__TITYIYIIIIXIKIAB`````````````````````
````````i`````````iYIIKIIIIXIXXKKIRIXX````````````````````
```````I````````_IIXXIIYIYIIXXXKKKIIIIR```````````````````
``````X``IXIIi`_IXXIIIYIIIXKXKKAEKIAIII```````````````````
`````I``XBBBBBRRIIXIKXXKXXBXBKKXKIKXIAIR``````````````````
```_```IXBBXXXBBXIIIXXRRXXXBXKXXAXKIIIYA``````````````````
``BXKi`XBI````_XRTYXRXXXRXXXKKKKXIAXKIIY``````````````````
```BBBiII_`_TTITX_TIKKBXXXKXKKKXIKXXXIYAB`````````````````
```I```TTYIXXIYi__`YXBKXXXXIKAKRKKKXRIYK``````````````````
``X``__TIYXXIIIi_```TIIYiTIXIXXXAKKIXIY```````````````````
``YKKITiIIIIIII```_```_TIKKXIIIIIXKXIIY```````````````````
``XIKIT``_iII`_iYIXKBXBXXIKXXKXKAIIYYIA```````````````````
```KIIT__``_TIIXXKXXXXKKXXBXXKXXXRKRAYB```````````````````
````iiiIiiTiTIXKBBXXKXAXXXKXKXKXXXBKKI````````````````````
```B`_iXY_``TXBBRXXKBAYRRKXXXRXXKKKXIB````````````````````
```XYiiXK``_iTYXBXXXBAKXXBBBXBXXKXB```````````````````````
```XX__`````_IIXXKXXXRXBKXKXBBKBXB````````````````````````
````BI```TXXXIXXXBXXXRKBXBBXXRKXB`````````````````````````
`````KTiIIYIXXXXBBBBXB`BBXXRBXXB``````````````````````````
`````TiYKIIKBXKKKBKKKBBBBXXXBKB```````````````````````````
`````BKXEYIi`___TYIYIIXBKBBBX`````````````````````````````
``````i_ii__iiYYIIIXIIXXRXXA``````````````````````````````
`````B__i__iTYIIIKKXBBBBB`BB``````````````````````````````
`````R`````iIXKKBB```````BBKB`````````````````````````````
`````B```iIXXKB``````````BBXXB````````````````````````````
``````IXKBB```````````````BBBB````````````````````````````
```````B``````````````````BXKB````````````````````````````
``````````````````````````BRBB````````````````````````````
``````````````````````````BBBIB```````BXXRXBRXXBBXB```````
````````````````````````BKKXXRX`BBBBXKBBB`BBB`BBKXB`XXB```
```````BXIIXIBB``````BBBXXBBXBBBBXXRB```````BBBRXBB``_iI``
```Bi`iIIIIXXIXRBXRXXXKXXB`BKXRB```````````BBXBRB`X_iiTIK`
`BiTXXXXXB``````I```````______iiiIIXB````BBXXXXKB``XXi_iI`
XXBBKKXKXXBXI_`_ii``````iRBBKRRXKXBXXXXKXXXXBXBXB```BI`iI`
_iiK`BKKXRY_iIXKXI```````iTITTKBXXRBXBXKKAIIXKXX`````B`_IB
IKXA``BRIiIXXi`````````iIXXIYTiiiiiIIXBBBXXXXKKB``````i`YB
XXK````BXX_``iIKI``````iB`B`BXBKBKKKKXBBXAAIBRRR``````i`YB
KK``````i`iXBBIi``````````````iiIXXXXRBBXIAYIXK```````I`IB
XK````IiII```_ii````_iYXBBBBBXXIIXIIYXXKXXXRXXB```````X`TR
XA````Xi`_IXKKXI```___i`BBBXBXRKBBXXBXRKKXIARRB```````I`YX
'
skeleton[1] = '
````````````````BYi``_iiTYIX``````````````````````````````
``````````````i````````_iiiiiiYB``````````````````````````
`````````````````````__`iiiiYiTYYYB```````````````````````
``````````B```````````_iTiYTYIYIIIIE``````````````````````
`````````K``````````_iTIIIIYIIXXXXEII`````````````````````
````````X``````````iTIXXXXIKXKXXKKIEIIB```````````````````
```````B`````___``iXKXXXIIIIYKBXAIAIAAA```````````````````
``````````YBRBRKiiXXXKXIXIIXXXRRXIAEIIIR``````````````````
````X````IBBBBBBBBXXKYIKRBBKXXKIKAAKIIYI``````````````````
```BIi``_RRBT``iXBBYXXXKRBKBXXKAXKIIIAIYK`````````````````
```BBBXiiBB```i__YBiIXXBXXRXXKXIAIEXIIIYI`````````````````
```BBBBXiR__IAIIIiIiTXXXKRKKKKIAIXKIIIYIB`````````````````
```X````iK_IIRXIIii``TXXKKKXIXXEXEXKXXIIB`````````````````
```i_iYIiIXTXIIIIii```_iTii_YXIIKKAKIXII``````````````````
```IAKKXiYXXIIIIT```_```_TYXBXIIYIAAIIYK``````````````````
```XIIII````_Ti_TTXKXKXXBBKXAXKRXXIIYYY```````````````````
````IIIT_iii_IYIXBBXXXXKKKXXXXXAKXXXXAI```````````````````
``````i_TIi_iiiYKBXRXBXXIIKBBKXKKXXXXXK```````````````````
```B`ii_TB_`__TKXKXKBBKIIRXXXBRXXKKXAX````````````````````
```YIi`_KXi```iTYBXKXBXAXXXXXBXXKXXBB`````````````````````
```BBK```````iIXKBBRBBKXBBRBXXXKXXB```````````````````````
``````_`_iXIIYXIKIXXBXXXBBBKBXXXXE````````````````````````
`````BiiYIKXYKIBKKXKBBBXBXBXXBKKR`````````````````````````
``````YIKKXiXKBIBAXBKBBXBXXBXKXXB`````````````````````````
``````BKIXIi_`_TiiYIIIXBXRXXRKB```````````````````````````
``````B_iiiiiiiTYIIXXKXXXBRKR`````````````````````````````
``````X____``iYXIIIXBBBBBB`BB`````````````````````````````
``````I`````iIKXXBB``````BXKK`````````````````````````````
``````X``_TXXXB```````````XXE`````````````````````````````
```````BRRRB``````````````BBXK````````````````````````````
``````````````````````````BBKB````````````````````````````
``````````````````````````BBBB````````````````````````````
```````````````````````````BBX````````BBXKXBKBBRXBX```````
````````````````````````BKXBXKK``BBBBXRBBBBB`BBBXBR```B```
```````XIiiiTiX`````BBBBXRBBBBXKXXXRXB```````BXBBX`BX`_iX`
```I_iIIXXXXXXXBBKXBXXBKB`BXXXKBB`B````````BBBKXBR`BX_iiIB
``YXEIXXBBBB````Xi```````i__iiiiiiIIXB````BBXXBBX```BXTiTK
iTXBBKKAKXKXXi__TYI``````YBBBBBKBXKXXBKIKXKBBXKXBB```BT`_I
iYIE``KIKBY`_YXXXXI```````_ITTYIKBXXXBBXXXAIKRXKB`````B`_I
IXIB``BIIiIKXT``````````TXBXIIITiTiiYIXKBXRXBXXX``````B_`Y
KKB````BIXT``iIXKI``````_BB`BBXAXXBBKKXXBXIARKBK```````T`I
XB``````T``YKKXT```````````````_iIXXBXKXBKKAYAXB```````X`T
IB````XiII_```TIi`````_iBBB`BBKXXXXXIIXXXKXXXKX````````X`i
XB````BY``iXXXBXI``````_XBBXBXBKBKXXXBKRXXIIIBB````````X`i
'
skeleton[2] = '
``````````````````Xii`_iTIXX``````````````````````````````
```````````````X````````_`_i_iiI``````````````````````````
`````````````i`````````___iiTiTTTiI```````````````````````
```````````B```````````___iiYTYYIYIIR`````````````````````
``````````B```````````___TYXKXXXIXXKAK````````````````````
`````````X``````````___IIXKBBXXXXKIIAII```````````````````
````````B``````IYTTi__IXRXKKXXIXXXKXIAYB``````````````````
```````B`````XRBBBBITIXKRRXBXXKXBKIIIAIAB`````````````````
`````I_`````XRB``B`BBXKXXXXKXXXXKKIAIIIYA`````````````````
````BIBBI_`TXBBT```XBBKXRKXKKXXKKXIAIIYYY`````````````````
````BXBBBX_YBX```YITIBYYXREAXKXKKIIIAAYYYB````````````````
````BBBTTXiYBT_iBXKT_XTiIXIXKKIAAAAIIIYYYB````````````````
````B```TT_TXi_AEEXTiI_`iYIKKIIIIIIAXIIYA`````````````````
````I_TBKBTTKXTIIIIiiX``__iIIIYIIIIKAIIYE`````````````````
````ITIIEXiiIIXIIIIII`_i_i___iTIXAIYAAYYB`````````````````
````BIYIII_i````_iiTIXXXKKKBKXBXKIRAYIYY``````````````````
````X``IIi_IiTTiYIXXBXBXXXXKXXKXXEXKKXAX``````````````````
````i``i_iiRYiiiiiYBXXXXXXKIKKXXXKKKXXXA``````````````````
```B_iiYTiiRX_``_YXXKXRKXKIABXBBXIIKIKIB``````````````````
```YIIY```Kii```_TYIXXBXKKIBRKXBKXXKIX````````````````````
````BBBY```````_YXKXBRXRXXKBXXXXKKXAA`````````````````````
```````I``iTIKKTIXXXXBBBKEKKBBBXKKIIR`````````````````````
```````X_iTiKKIIXBBXBBRRBXREBXKXKXIB``````````````````````
```````XTIKKRITIKKBKBBKXKXKXBKXKIXX```````````````````````
````````RIYIITi___TYTIXBXKXRXKXIIR````````````````````````
````````i__iiii_iTIXIXXXBXBRKAKR``````````````````````````
```````B__`__``_iIXXKKRBXKXBB`````````````````````````````
```````B```````TXKXBRB````BBIB````````````````````````````
````````i```_IKXR`````````BBKB````````````````````````````
`````````BBBBB``````````````BB````````````````````````````
``````````````````````````BXRR````````````````````````````
``````````````````````````BXXX````````````````````````````
````````````````````````````BXB```````````BXXXBBBBB```````
`````````````````````````XKBXXK``````BBKBXBXXBRRRBBXB`````
```````BIXXXXXIB```````BBKXXBBBXBRXXXBXBB``````BBXXK``BXB`
```Xi_TIIXXXIIYIYBXBBBXBBBBBXXKBBBBB`````````BXXBKB`BBBXBK
``iIXIXXR`````````IYITi_```_i____iYXB``````XKBXRBKB`BXXBBB
iYBBRXXEKRXBKBXi__ii``````iKBBKKKXXXKXXKXRXBBXXXBB```BKXBX
iYYB`BXAXKXIi_TIXXBI```````IXIXBXXRKXKBXBKKIIXBXKR`````BY_
XXIB``BKATiYKXXT``````````IYTTiiiiiiTIXXBBXXAKBBBB``````Y_
XXB````EXYXI```iIXX```````T`BBKBBRKRXXXXXXXXXBRBB```````X`
IB`````BKT``iXBKKI``````````````iiXKBXXKBRKIIIXBR```````B`
AB`````IiYXI````ii`````_`YXBRBXKIYYIXITIXXKXBERXB````````i
X``````IK_`iYXXXBB_```iiiiXBBXBKBBBXBXBRRKIIXKBB`````````T
'
skeleton[3] = '
```````````````````BT____TYXB`````````````````````````````
`````````````````I````````__``iiYB````````````````````````
``````````````B```````````____iiTiiI``````````````````````
`````````````X```````````____iTYITIIIR````````````````````
````````````I``````````````_iiYIXIXIIII```````````````````
```````````_````````````_`iiYIKKXKKKXKIK``````````````````
``````````_````````IBKKXYiiYXKKIKKXKKIIYX`````````````````
`````````i````````BBBBBBBXYXKIKKBKXKKXAII`````````````````
```````XYBBIi_``YRBB`BBBBBBBXKKKXXKKKKIYII````````````````
```````IRBBRBIiiKBB_```_IBBBBIAAKKEAIIYIYIB```````````````
``````KXBBBRBBYYXBI``TAKYYBRiKIAAIKKEIYYTYI```````````````
``````BBT````IITBB`_YBBKI_BX_XXXIIAAIYYYYYK```````````````
``````B```IKAI_iRB_TXKEXT_KI`iYIAIAIIYYYYYB```````````````
``````B``AXREK_iXKXYIIIIiYBI`_iTIIIIIYYIYI````````````````
``````B_TIXXXY__YIKKIIYIKBXTiTiiiTiiiIIIYKB```````````````
``````i_TIIIIi_iii_``_iYXXBBKXXXXXXBBKIIIR````````````````
`````B```iXIiiiRYTTYIXXXRXBBBBBXRXAKKIXKY`````````````````
`````_```__YiiiKIiTiTTYXBKBBKBKXAKKRKIKKAB````````````````
```B`iITiTYi__IKRI__iTXBRXXXBXIIKXKBEIXAIR````````````````
```RKXXXXY_```i`````iiIXXXBKXAIXXKBKXIIYB`````````````````
``````````_```````iTIKXXKBXXAAXXKXXXIYYE``````````````````
``````````__iIIIIKXIIKXBBBKKKKB``BXRXIY```````````````````
``````````TiiTITYB`BBXBBBKKBXBB``BKRIIK```````````````````
``````````IKBXBEA`IEKRBXBBKBARE`XKIIAK````````````````````
``````````BYYYiiYIi_iiYXXBXXKXXAIAIIIB````````````````````
``````````X`iiTTTiYiTIXXRRXXKXXKAAIR``````````````````````
``````````T`i__````_TXXXXBBKKKXARRB```````````````````````
``````````Y_``````_YXRXXBBBXRBB```````````````````````````
``````````Ii``_iiXRBB`````BKXX````````````````````````````
``````````````B`B`````````BBB`````````````````````````````
``````````````````````````BBBA````````````````````````````
```````````````````````````BBEB```````````````````````````
````````````````````````````BBB```````````````````````````
`````````````````````````BBKRBX````````BBBXXXBBXBBBBBB````
```````BXXXIXIKB````````BBXXXXXXBBBBBXXBBBBBBBB`BBRXXX````
```Xi`YIKXXXIIIYTi_KXXXXXXBBBXRBBBBXKXBB``````BBBBKXBB`BXK
`BXIKXKXB`````````BBYiRBBXKXKXXXXBXXB```````BXXXRXXB`BRXBX
iiBBBKKIIXKBKB``XT_ii_``_iYXXRXXBXIIIIIXB`BXKBRXXBK```BBXK
iYIB`BAYAXXXXi`_IXXB`I``````_IXBBBBXBXBXXRKXKBXXXXB```BRRB
XBAB``RAIIT`TXXKXT_````````_ii__iiiiiTXXXBXXAAXBXX```````B
BKB```BXIITXXX_``iIXX```````iBB`BBBKIXIIYIIKXXXRXB````````
K``````BEIXi``iXXBBXi`````````i_iYIXKXXBBBXAKIIBXB```````B
B```````i_TIXI_```__``````_iIKXXXXIITTIYIXXBBIIIX`````````
B``````BIKI_``iIXKRBi```_`_iXBBBB`BBBXXBXKXIIKXRB`````````
'
skeleton[4] = '
```````````````````````````XT__iTXB```````````````````````
```````````````````````X```````____iTX````````````````````
````````````````````T`````````i_iiiiiYTTB`````````````````
`````````````````````````````i___iiiTiTYYIB```````````````
`````````````````B``````````__`iiiiiiiiTiYIR``````````````
````````````````i````````___`__YTi_`__iiYIIAX`````````````
```````````````i``````i_iii_`___```iIKXYiYIIIR````````````
``````````````X````_XBBBBXXTTii``iBBBBXBXIIIAY````````````
``````````````````TBBBBBBBBBBXTXXKBBBBBRBXRIIIA```````````
`````````````B```YBBBXTIXBBBXXKRKRBXIIXBBBBYYYI```````````
`````````````B```XBX```_TYBBXIXIKX````AIBBXEYYY```````````
`````````````B_``BB```_AKKYBXiIXI```_AEAARXXIYK```````````
``````````````X`iBX`_TIREEiKIiIAK__TIXEXFRBXIY````````````
``````````````B`_KBiTIIIXAiBI_KAKITIIIITIBRRXE````````````
``````````````X`_TIXIIIIIIXBIiXIAKIIIIIXBXXXXB````````````
````````````Bi``__`iiIXKXBXBYYXXXYIIXXBBXXBRBRRB``````````
`````````I````iIIYi_TIKXXBBBIIRBXBKXKKXBXRXXBXXKKKAB``````
`````````i_TYXRXXKIIXXKXXIIIIXBXXXXKXKBBKXBBXXKBRXEB``````
``````````BXXXRBRBXXIIIiTTiiREEBBXIIXBBXKKXAIBXXBB````````
``````````````XKKXXBX__``__`___iiiTYKKIIAIIIBK````````````
``````````````IBKRBY````````_iTiIYIXXAIIIIAKXAB```````````
``````````````BBXBBTiiYTATAIXBXKXXXBBXIIYKBRXB````````````
```````````````BXR`TiiYYIYKKXBIXB`BXBXXRB`BKK`````````````
```````````````BXBBIXBXKXXBBRXXKBRXRBKAIXBXIB`````````````
````````````````XXBTTXI__iiIIIBKBXBKRKKAXXIK``````````````
````````````````Bi`````iTYIXXXXKXXBRXXIYYII```````````````
`````````````````i``_`_iTiiiiiTTTYXKKKIYYIE```````````````
````````````````Bi__iiTTi````_i_iIXXKXXYYYK```````````````
```````````````````BBBBXXYTTTYIXRKXKRBBB``````````````````
````````````````````````````BXBKBB````````````````````````
`````````````````````````````BB```````````````````````````
````````````````````````````BXKB``````````````````````````
````````````````````````````BBKB``````````````````````````
````````````````````````````BBBB``````````````````````````
```````ITiiTiIIIX``````````XXKXXXB`````````BBBBBBBBBB`````
````i`_XRXXXXRKXKXIYTYIIIYiXRKBBXRBXBXBBBBXXXXBKBXBKXBXX``
`XX`BBKYIKXB```````BBBBBBBBKTIIBBBBBXBBB````````BBBBBBKXB`
`_TI``BIYYAIIX```````BITiTTi_```iKXBRKXBB````BXXXXBBXB``BR
iTXKE`BKYIAXXKKX`BT`TIIXXBR_```_iiIKBBXBBKXIXBKXBXXXK``BRB
IXXA```BIIIKET__TIXIYYTiii`````____iiTXBRBBBXKIIBBBXB```BX
XKB`````KIYXiiIKXIXY```iTIY_`````_iYIIYXXXBKKXRIIBXX``````
KB``````RYIIXXXIi``_YXBB```X````___iB`BBRXXXKXXAXXXB``````
X````````RYi__iTIXYT___```__``_____iTiii__iIKBXXIYX```````
K````````BYTYXBXEY``iIIXXBBX_`_`iiTIXBXXXKXXKIIKKKR```````
'
skeleton[5] = '
````````````````````````````````BXIiiiiYX`````````````````
````````````````````````````Y`````````iiiiIB``````````````
`````````````````````````i`````````__iiTiTTIII````````````
```````````````````````Y`````````__iiiiiiTIIIIXB``````````
``````````````````````i``````````___iiiTTIIIIIXIR`````````
````````````````````X`````````````````_iYIYYIXIIIE````````
```````````````````B```````````````_YXXBXIYTIIXKXII```````
```````````````````i`````````````_IXBRBBRBXIIIi_`_iK``````
````````````````````````````````TRXBBBBBBBBXIKTYXKXRIB````
``````````````````K`_`__i_i````iKKBBI`_IBBBBKKBEKRBBXX````
``````````````````i__iiTi_`````IIKX````TIBBBRXEKBBBBBX````
``````````````````i_iii__`````iIIK```_TIAABBXXXIIIIIBB````
``````````````````Yii____`````TIII__TIYXAYBBXIIIIIIXAX````
``````````````````X_`___`````iIKIIITIIIIYRBXBXIIIIIIYA````
``````````````````R````````iiIIIIIXIIIIIIBXKRIYIYIIIFAB```
````````````````````iTIIYTTXXXXBKXIYIIKBBBBXKXIIIYIIBKB```
```````````````````_XBBKXKBXXBXBKXKXKRXXBKBRBKRIXXXBBKK```
```````````````````IXXXXKBXBXBXXXBXXRXXBBXXRBKIXKXKKIIAB``
``````````````````XiTXBBRBXBXXBXXXKXKXXXBBRBBRXKXAXEIAKAK`
```````````````````Ti`_YKBXXKXKXBBBXKXXXKKBBRBXKEXAIXAXKIB
```````````````````X___iKKXBBXBBBBRKXYTYYXXKBXKXAYKB``````
````````````````````TiiiIXBBBBBBKRRBRIIXXKKBBKKXII````````
````````````````````BTTTYIB``BBBBBXRBKXRXXXXXKXBKK````````
`````````````````````RiTTiiX`KKRKXX``BBKBBBRXXXRKX````````
``````````````````````I___````_IXBRBBXYXXRBXBKBAAB````````
```````````````````````X_``````__iiiiTXBXXKBXREIIB````````
`````````````````````````Y___i____iiTIXXRXKXXREXIA````````
````````````````````````````BXXIIIIXXXXIYIXKXKKXIK````````
`````````````````````````````BXXXB``BBBKXIIYXKAIIA````````
`````````````````````````````KIXK```````BRBXBKKB``````````
````````````````````````````B_IB``````````````````````````
````````````````````````````XiKX``````````````````````````
````````````````````````````B`BB``````````````````````````
````````BYiTYIYYYIXB````````_`YRiX````````````````````````
```````XTIIAKBBRXXXBXIXXB`BI`IXTYKB```````````````````````
```XiiB`BBEIB``````BBXBKXKXIXIB`BBRTYiiYBXXKXBXXBBXXBR````
````iIII`BIYIYAB```````````B`iYYYYYTTIIRBBB```B````BBBXBK`
`B``YXEI`BXYIAAIB```````XYTTIXXXX_ii_iiXBXXBBBBBXXXXXXBXBB
`B_TXIK``BXYIAIIAE`Y__iYKXBXXKKBK`_i_iiIBIKBXXXXBXXXBB`BXB
`X_IIB````XYIIIKiiYXXKKKKXKI``____`__iiiiiTXKXBXYRBX```BKB
`TTXK`````BIYYYXKKXIB`BIi`iYIXKBBX`___iiiXKKYYKXXABB````BX
`_YAB`````BIYYIIIY_``iTYIXXXKKBBBB_``_iiiiXXXKRXAXB``````B
X_XEB``````XYI__TYXXXKKKBXi__iiYYIXTiTTiTYIYTiiYIKIYB````B
iiIB```````BAYXKAIIBBXT_`iiXKBBB``BIiTTTYIIRXXXXXIIAB````B
'
skeleton[6] = '
````````````````````````````````XIYTTYTYB`````````````````
```````````````````````````Xi`````````iiiTTX``````````````
````````````````````````T``````````__iiTTIYTYI````````````
``````````````````````I``````````___iiiiIIYYYIIB``````````
`````````````````````T``````````_``_iiiTYYYIIXXI``````````
```````````````````````````_i_```````_`__iYXIRAIIR````````
```````````````````````````_i_```_``___iYXXXIXAAIIR```````
``````````````````B``````_____``_i```iIBBBBXXKIXIII```````
`````````````````B```_``_i_ii___````iIXB`BBBBRKYITiiIR````
`````````````````Y`__i_iTTTTii_````TXRBXXXXBBBBIEXAEKIB```
`````````````````i`iiiTTTiTTi_````iXARX```iTXBBXXXXXRKB```
`````````````````Ti_iiiii___``````iXKX_``iIIYBBREXXXBBE```
`````````````````T__iiiii`````````IKIIiTYIIIFBRKIIIYIIB```
`````````````````X______`````````TXKIIIIIYIYYBBKIYIIYTR```
`````````````````B````````__iiTTTIXBXKIIIIIYXBBXIIIIIYE```
``````````````````i```_XXBBKKKXBXBXRRRXIKBBBBKKKIIIITIB```
``````````````````X`iXBKBXABXXXBXXXXXXXXRXKKXXXKIYIIII````
``````````````````BTiIXXXXKXKBKBBXXKXBBXXRBKXKKXIERBXIR```
``````````````````BYYY_iTXIXXXXXBXXXXXXXXBXKXXBXAAAIIIA```
```````````````````BTi__iiAXKXBBBKBKXRBBKBXRXBBRKIIYYIIR``
````````````````````XiiiiiXXBBXXRBRXXXBXBBRXKKKIIAYAKXRX``
`````````````````````IiTYTXRBBRRBBRKXXBRXBXXXKXAIAA```````
`````````````````````BITYYIIX`RBRRBBBBRBRBRKKRXEXBA```````
``````````````````````BTTTiiiXBiIBRBRB``BBBBKBKKKKX```````
```````````````````````Bi__ii_````iKRXBBBRXBBRKBXKR```````
`````````````````````````Ki```___i__iXBXRXXXXKKXAX````````
```````````````````````````BIiiiiiiTYTIXXXKRXXXKIIB```````
````````````````````````````YBBBBBKXXXXBBXXKKXIIKYR```````
```````````````````````````B_XXB``````BBRBXXRXXEIYB```````
```````````````````````````BBBR````````````BXBXAAR````````
```````````````````````````IXIB```````````````B```````````
``````````````````````````T`XK````````````````````````````
`````````XYTIIIK`````````BiIB`````````````````````````````
```````TiTIIKXRXXIIX`````X``YX`i``````````````````````````
```BXB`XXXE``B`B`BXKKIIIYi_XKKKKK`````````````````````````
``_`iiIBKXIYR```````BBRKXXXKB``RBXITTTIXBBXBXRRBXKXB``````
`_``IIYABAYIYY```````````i`TIIYITiiiiiIB`````````BKXXK````
`X`TKIKBBXYYYYYB`````XYTiTIXXKBBIii_iiIKXXXXBXBKXXXBXBBB``
`X`IAR```BITIAIIITi_iIKXBXXXRBBBX`i_iTTIIXXXXIKBBKB`BXBXI`
`i_XI````KIYYIKXXKKRBKXBXKi__iiiYTi_iiiiTiiTXKIAXB``BBBXI`
`iTIB````BIYYYIIAA``BITi_iYXKBBRBI__`_iiIKRXIXAXB````XBXK`
B_IX`````BKYYTYi___iTIXXKIKKBBBBXT_`_iYYiYXIXRKAE`````KBB`
TiIB``````BIYBYIXXBBBBB`BI___YIXXXXXTTTiTIIIIiiIKIB``BXB``
_TIB``````XYYIIIIB`BIT__iTIXXBBB`IIIiTTYXIIYBXKKKIR``XXB``
'

loop do
  skeleton.each do |i|
    puts i
    sleep 0.1
    system 'clear'
  end
  skeleton.reverse_each do |i|
    puts i
    sleep 0.1
    system 'clear'
  end
end